export const theme = {
    PublicSansLight: "Public Sans Light",
    PublicSansRegular: "Public Sans Regular",
    PublicSansMedium: "Public Sans Medium",
    PublicSansSemiBold: "Public Sans SemiBold",
    PublicSansBold: "Public Sans Bold",
    PublicSansBlack: "Public Sans Black",
    AnteCFBlack: "Ante Cf Black",
    maxWidth: '1440px',
    customFullHeight: 'calc(var(--vh, 1vh) * 100)',
    white: "#ffffff",
    black: "#000",
    sky: "#6fc9ff",
    skyLight: "#98d7fe",
    magenta: "#4e4dc9",
    elasticPink: "#f3a1c8",
    lime: "#86eda9",
    snowflake: "#eff0f0",
    catsCream: "#e8e7e4",
}